version: "3.8"
services:
  php:
    container_name: evd-php
    build:
      context: ./
      dockerfile: "./docker/php/Dockerfile"
      args:
        - BUILD_UID=${DOCKER_UID}
        - BUILD_GID=${DOCKER_GID}
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - /var/www/html/node_modules
      - /var/www/html/.git
      - ./public:/var/www/html/public:delegated

  nginx:
    container_name: evd-nginx
    image: wodby/nginx
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html/public
    volumes:
      - ./public:/var/www/html/public:delegated
    networks:
      - default
      - traefik-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-gateway"
      - "traefik.http.routers.evd-nginx.rule=Host(`eloquent-viewable-demo.test`) || Host(`www.eloquent-viewable-demo.test`)"
      - "traefik.http.routers.evd-nginx.entrypoints=https"
      - "traefik.http.routers.evd-nginx.tls=true"

  mariadb:
    container_name: evd-mariadb
    image: mariadb:10.4
    command: --init-file /data/application/init.sql
    volumes:
      - ./docker/mariadb/sql/init.sql:/data/application/init.sql
      - mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: eloquent-viewable_demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 127.0.0.1:34063:3306

  redis:
    image: redis:4-alpine
    container_name: evd-redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mailhog:
    image: mailhog/mailhog
    container_name: evd-mailhog
    networks:
      - default
      - traefik-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-gateway"
      - "traefik.http.services.evd-mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.evd-mailhog.rule=Host(`mailhog.eloquent-viewable-demo.test`)"
      - "traefik.http.routers.evd-mailhog.entrypoints=https"
      - "traefik.http.routers.evd-mailhog.tls=true"

volumes:
  mariadb:
    driver: local
  redis:
    driver: local

# Make the externally created network "traefik-gateway" available as network "default"
# docker network create traefik-gateway
networks:
  traefik-gateway:
    external:
      name: traefik-gateway
